version: '3.7'
services:
  zookeeper:
    image: bitnami/zookeeper:3.7.0
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka:
    image: bitnami/kafka:2.8.1
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: "yes"

  device:
    build: ./device
    restart: always
    depends_on:
      - kafka
    command: node device.js
    deploy:
      replicas: 4

  consumer:
    build: ./consumer
    restart: always
    depends_on:
      - device
    command: node consumer.js
    deploy:
      replicas: 1
    volumes:
      - ./consumer/data/:/usr/src/app/data/

  kafka-setup:
    image: bitnami/kafka:2.8.1
    depends_on:
      - kafka
    command: >
      bash -c "
      kafka-topics.sh --create --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 --topic temperatures && 
      sleep infinity"

