version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  device:
    build: ./device
    restart: always
    depends_on:
      - rabbitmq
    command: node device.js
    deploy:
      replicas: 4

  consumer:
    build: ./consumer
    restart: always
    depends_on:
      - device
    command: node consumer.js
    deploy:
      replicas: 1
    volumes:
      - ./consumer/data/:/usr/src/app/data/
